import { readdir, readFile, writeFile } from 'node:fs/promises';
import { relative, join } from 'node:path';
import { fileURLToPath } from 'node:url';

async function listFiles(dir) {
  return (await Promise.all((await readdir(dir, { withFileTypes: true })).map(entry => entry.isDirectory() ? listFiles(join(dir, entry.name)) : [join(dir, entry.name)]))).flat();
}

// Generate deployment rules from the actual redirect pages, keeping these in
// sync with new posts and custom permalinks without a second URL registry.
export default function staticSeo() {
  return {
    name: 'static-seo-deployment',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const redirects = [];
        for (const file of (await listFiles(root)).filter(path => path.endsWith('.html'))) {
          const html = await readFile(file, 'utf8');
          const target = html.match(/http-equiv="refresh"[^>]*content="[^";]*;\s*url=([^" ]+)/i)?.[1];
          if (!target?.startsWith('/')) continue;
          const source = `/${relative(root, file).replaceAll('\\', '/').replace(/index\.html$/, '').replace(/\.html$/, '')}`;
          redirects.push({ source, target });
        }
        const rules = ['# Generated by Astro. Deploy with the rest of dist/.', ...redirects.flatMap(({ source, target }) => [
          `${source} ${target} 301`,
          ...(source.endsWith('/') ? [`${source.slice(0, -1)} ${target} 301`] : []),
        ])];
        await writeFile(join(root, '_redirects'), `${rules.join('\n')}\n`);
        await writeFile(join(root, 'redirects.json'), JSON.stringify(redirects, null, 2));
        await writeFile(join(root, '_headers'), '# Content-hashed Astro assets can be cached permanently.\n/_astro/*\n  Cache-Control: public, max-age=31536000, immutable\n');
        logger.info(`Generated HTTP 301 rules for ${redirects.length} migration URLs and hashed-asset cache headers.`);
      },
    },
  };
}
