baseURL: "https://mishalabdullah.xyz"
languageCode: "en-us"
title: "Mishal Abdullah"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Mishal Abdullah" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mishal."
    subtitle: "Badass Programmer"
    content: "
    1. having extremely favorable qualities.\n
    2. pertaining to a person or thing that is rugged, strong, and/or ready to show these qualities.
"
    image: /images/mishal-beckn.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Mishalabdullah
        - icon: fab fa-x-twitter
          url: https://x.com/mishalabdula
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/mishalat/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "Whoami"
    image: "/images/profile_test.png"
    content: |-
      A badass programmer with a passion for Hacking things. Constantly building highly niche tools and working on projects that other developers fear to work. 

      I am currently working on a building Open Networks Using Beckn protcol and also building cool AI based products.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Beckn"
        - "JavaScript"
        - "Python"
        - "Node"
        - "React"
        - "Nextjs"
        - "Django"
        - "tailwind"


  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Backend Developer"
        company: "Gtech Mulearn"
        companyUrl: "https://mulearn.org"
        date: "Sep 2023 - Present"
        featuredLink:
          name: "Certificate"
          enable: false
          url: "/docs/trizwit_certfcte_Blockchain.pdf"
        info:
          enable: true
          content: Blockchain Developer at Trizwit labs.
        content: |
          I work as a backend developer at [Gtech Mulearn](https://mulearn.org), mainly building the backend of the platform using Django and occasionally doing some frontend work. Sometimes I build things using unfamiliar tech stacks.

          Tech Stack:- Python, Django, JavaScript, MySQL, React
          - Covering tech news in a event called Faya Port 80.
          - Helping to run events and workshops.




      - job: "Blockchain Developer"
        company: "Trizwit Labs"
        companyUrl: "https://trizwit.com/"
        date: "May 2023 - Sep 2023"
        featuredLink:
          name: "Certificate"
          enable: true
          url: "/docs/trizwit_certfcte_Blockchain.pdf"
        info:
          enable: true
          content: Blockchain Developer at Trizwit labs.
        content: |
          I was working as a blockchain developer at [Trizwit Labs.](https://trizwit.com) working remote.I was tasked to build a DAPP which was designed to add certificated to the blockchain and make it tamper proof.

          Tech Stack:- JavaScript, Tailwind, Nextjs, Solidity, Wagmi, MongoDB
          - Created the frontend and backend of the DAPP using Nextjs and Tailwind.
          - Create the smart contract using Solidity and deployed it on the Mumbai testnet.


  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Beckn Kerala Chapter Lead
        content: I am the lead of the beckn Kerala chapter.Introducing people to beckn teaching them about beckn.
      - title: Code4Goverment Commnunity Leader (Beckn)
        content: helping and mentoring students in the C4GT Commnunity regarding the beckn protocol.
      - title: Trivial Ideas Winner II
        content: Won the second prize for Creating an AI based image transcriber app.
        url: "https://www.linkedin.com/posts/mishalat_result-of-something-cool-which-i-built-a-activity-7171445440280813569-EoMS?utm_source=share&utm_medium=member_desktop"
        # image: /images/achievment.jpg
      - title: CodeStorm Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        url: https://www.linkedin.com/posts/mulearn_softwarewinners-activity-7099771456217108480-1ZNu?utm_source=share&utm_medium=member_desktop
        # image: /images/achievment.jpg
      - title: Sandshore Hackathon Winner
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://www.linkedin.com/posts/mulearn_app-activity-7133794569283895296-aMXi?utm_source=share&utm_medium=member_desktop"
        # image: /images/achievment.jpg

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Beckn Onix GUI
        content: A GUI made for the beckn-onix installer.This is now part of the main beckn-onix repo
        image: /images/beckn-gui.png
        featured:
          name: repo
          link: https://github.com/beckn/beckn-onix
        badges:
          - "Nextjs"
          - "Nodejs"
          - "Javascript"
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/Mishalabdullah/beckn-onix-gui/
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Voicetoblogs.com
        content: A web app used to create blogs from the user voice input and also works as audio note taking app where all voice recordings are transcribed and stored.
        image: /images/v2b.png
        featured:
          name: website
          link: https://voicetoblogs.com
        badges:
          - "AI"
          - "Nextjs"
          - "javascript"
        links:
          # - icon: fab fa-github
          #   url: https://github.com/gurusabarish/converter

      - title: brainrag.com
        content: An AI based note taking app where you cannot view your notes but access your notes though a prompt.
        image: /images/image.png
        featured:
          name: webstie
          link: https://brainrag.com
        badges:
          - "AI"
          - "Nextjs"
          - "Javascript"
        links:
          # - icon: fab fa-github
          #   url: https://github.com/gurusabarish/HugoProfileV2

  footer:
  #   recentPosts:
  #     path: "blogs"
  #     count: 3
  #     title: Recent Posts
  #     enable: true
  #     disableFeaturedImage: false
  #   socialNetworks:
  #     github: https://github.com
  #     linkedin: https://linkedin.com
  #     twitter: https://twitter.com
  #     instagram: https://instagram.com
  #     facebook: https://facebook.com

  # List pages like blogs and posts
  # listPages:
  #   disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"
